### ISSUE TITLE
有相应的论文吗

### ISSUE THREAD

**Issue by tiankong1993** [happynear/FaceVerification#37]
抱歉打扰您，请问对应的人脸验证论文吗，没有看到论文的链接呢

**Comment by happynear** [comment]
就是照着CASIA-webface那篇论文的描述复现的。

**Comment by tiankong1993** [comment]
本来只是抱着尝试的心态，没想到您回复了，十分感谢。为了运行您的demo，我看了所有的留言及回复，也经常来看看您这里别人所提的问题，我在这里还是有两个问题想请教一个:（1）实验今年需要很多.mat数据集，比如lpb_lfw.mat，我看评论里面有的说感谢您提供的.mat文件，但是我一直没找到这些文件，你的博客及github我都没有找到，还有评论说可以在JB作者主页可以下到，我一直都没太看懂到底怎么去找到这些数据集，还望指教。（2）网上对于深度学习的描述一般是用来做识别或者分类，如果用来做人脸验证的话，那不就是两张脸的对比，是单独提取两张脸的特征吗？那么训练模型的有什么用处吗？    还望您能抽出些许时间看看我的问题，非常期待您的回复，感恩^ω^

**Comment by happynear** [comment]
这些文件是我两年多以前写Joint Beyesian的时候下载的，现在已经找不到了。。

训练模型是为了提取特征，使得提取出的特征满足相同身份更近，不同身份更远的特性。

**Comment by tiankong1993** [comment]
哦哦这样啊，还是谢谢您了，但是如果没有这些.mat文件这个face verification的代码不是运行不了了啊，还是说得自己去写呢，我看评论里面今年还有人下载过呢，这是怎么回事啊？
