### ISSUE TITLE
关于特征提取

### ISSUE THREAD

**Issue by tiankong1993** [happynear/FaceVerification#40]
请问特征提取中的f =f{1}是什么意思呢，我调试看好象是取了f的第一列，为什么只取第一列呢，后面的都不要了吗，打扰了

**Comment by happynear** [comment]
是取出caffe输出的所有blob中的第一个（实际上也就只有一个）。

**Comment by tiankong1993** [comment]
感谢您的回复，还有一个问题想请教一下，deploy文件中 第一个input_dim 是写2而不是6000这是为什么呢
