### ISSUE TITLE
Face Verification(Caffe Newbie)

### ISSUE THREAD

**Issue by linng85** [happynear/FaceVerification#5]
Hi, i am new to deep learning and Caffe, may i know how should i use your face verification code? I had built the windows caffe as mentioned in your blog and test the MNist as well. But what should i do to proceed face verification with Caffe?

**Comment by happynear** [comment]
The codes in this repo is indeedly messy. It is only for those who is familiar enough to caffe and face recognition algorithms, and I do not have time to give a step-by-step guidence.

To get start, I suggest you to read some paper first, such as deepid, deepid2, deepface, facenet etc. Another important thing is to learn how to use caffe. After you have learned all these, you will naturally know  what these codes are written for.

**Comment by linng85** [comment]
Ok. Thanks a lot for the information. By the way, the solution for this FaceVerification is for Matlab?

**Comment by happynear** [comment]
Partly yes. The caffe related files (prototxt) are written for caffe executable program.
