### ISSUE TITLE
请问能给我发一份pairlist_lfw.mat & lbp_lfw.mat么？

### ISSUE THREAD

**Issue by scottyyih** [happynear/FaceVerification#52]
用于测试Joint Bayesian，谢谢！

**Comment by happynear** [comment]
年代太过久远，我也找不到了。

**Comment by mike07026** [comment]
找到了，还是作者@happynear自己的链接..
https://pan.baidu.com/s/1kTkM49D#list/path=%2F&parentPath=%2Fdatasets

**Comment by happynear** [comment]
嗯，后来又有人问我要，我从一个很老的电脑上翻出来了。。
