### ISSUE TITLE
关于使用yandong的model的aligment问题

### ISSUE THREAD

**Issue by scottyyih** [happynear/FaceVerification#55]
你好：
        对于使用yandong的model center face，使用了下面两个函数做了align操作：
        Tfm =  cp2tform(facial5points', coord5points', 'similarity');
        cropImg = imtransform(img, Tfm, 'XData', [1 imgSize(2)],...
                                      'YData', [1 imgSize(1)], 'Size', imgSize);
        请问这两个函数是通过什么算法实现的？怎么保证在做对齐时5个landmark都兼顾到？谢谢

**Comment by happynear** [comment]
搜一下“相似变换”。
