### ISSUE TITLE
The accuracy about your center-face model on LFW

### ISSUE THREAD

**Issue by kalyo-zjl** [happynear/FaceVerification#58]
hi, @happynear 
Thanks for sharing the model and code. I followed your step to test the accuracy on LFW dataset. The final accuracy is 96%, which doesn't match the result you reported. I used your model and aligned LFW images. 
Since I'm in linux, I can't use your caffe version, I mannully change the center_loss_ms.prototxt file and flip images in matlab code. Is accuracy of 96% right?

**Comment by kalyo-zjl** [comment]
hi,
I have noted that your caffe-windows supports linux now. But even if using your caffe and original center_loss_ms.prototxt, I can still only get 96% accuracy. I just follow the steps: getPairs.m ReadFeatureLFW.m and lfwPCA.m. I don't modify anything except some paths.

**Comment by happynear** [comment]
I don't know from which step you made errors. This model can get 99.3% on LFW and I tested it several times. I have provided another model at https://pan.baidu.com/s/1i4Q4vD7 , which should get 99.21% on LFW. You may try this and see if it can work.

**Comment by kalyo-zjl** [comment]
@happynear Thanks for your reply. I have tested the model at https://pan.baidu.com/s/1i4Q4vD7, using the prototxt from http://pan.baidu.com/s/1jIJT4Rc and it gets 99.2167% by 10-fold PCA evaluation. So maybe the problem is in the caffemodel rather than matlab code.
BTW, could you please share the train.txt and val.txt in training 99.2167% model?
Thanks.

**Comment by happynear** [comment]
If you want to train by yourself, you need to read my paper: https://arxiv.org/abs/1704.06369 , and this is the project page: https://github.com/happynear/NormFace .

**Comment by kalyo-zjl** [comment]
@happynear 
OK, thanks!
