### ISSUE TITLE
请问网络收敛的速度

### ISSUE THREAD

**Issue by thuhuwei** [happynear/FaceVerification#6]
你好，非常感谢共享关于人脸的网络模型。我现在有一个问题，就是我同样使用Casia的数据，但是训练时候网络收敛的非常慢，lr = 0.01时，迭代几千次后 softmax_loss 依然在 8.9 左右， test accuracy 在 0.001 左右，请问这是否有问题？ 谢谢！

**Comment by happynear** [comment]
嗯，这样一般是有问题的。但原因太多了，学习率、初始化、损失函数等都有可能造成这个结果。

**Comment by thuhuwei** [comment]
但我使用的就是Github/faceverification/caffe_proto中提供的配置文件
CASIA_train_test.prototxt和mnist_siamese_solver.prototxt，唯一改动的就是 lr 设为 0.01

因为我并不是使用提供dcaffe-windows，所有我是手工添加的sanity layer以及 fillerparameter 中 alpha 参数。不知道除此之外还有没有需要处理的？

**Comment by happynear** [comment]
没有了，这还下降不了的话，只能怀疑数据问题了。减均值、除128之类的事做了么？

**Comment by thuhuwei** [comment]
这些都作了，我再检查一下吧。请问你在lr=0.01迭代一万次后大概准确率能有多少？

**Comment by happynear** [comment]
一万次的结果早就不记得了，但一开始下降得还是蛮快的。

**Comment by thuhuwei** [comment]
多谢。我是通过caffe自带的 create_imagenet.sh 和 make_imagenet_mean.sh 创建的lmdb数据。原始图像也是casia webface提供的normalized图像，应该和你用的是一个数据库。按说不应该有数据输入的错误。我再仔细检查一下。

**Comment by thuhuwei** [comment]
请问能否共享你训练好的模型或者snapshot？我想验证一下我的数据是否有问题。谢谢！

**Comment by happynear** [comment]
抱歉，跟别人有协议的，model不外传。
