### ISSUE TITLE
Why we use PCA just on 9-folder?

### ISSUE THREAD

**Issue by xiaoxiongli** [happynear/FaceVerification#63]
Dear happynear,

@happynear 

 i find that you just use PCA on **9 folders**(train_idx), and apply the pca result to 10 folders(train_idx+test_idx):

**PCA:**   [U,mu,vars] = pca( [F1_mu(**train_idx**,:); F2_mu(**train_idx**,:)]' );
**apply PCA:**   [F1PCA,F1PCAHat,~] = pcaApply( F1_mu', U, mu, dims );

so i wonder that why NOT use PCA on all of the folders other than just in 9 folders?

**Comment by happynear** [comment]
We should **never** see test examples in **any** way.
