### ISSUE TITLE
About joint bayesian

### ISSUE THREAD

**Issue by kensun0** [happynear/FaceVerification#7]
你好。
都是中国的，我就说中文了。
这段JB的代码，我只复现了在原文提供的那个数据集上的性能。
请问你JB的结果有没有好于L2的时候？
即使我用webface去训练JB，结果也没L2或者PCA好：（

**Comment by happynear** [comment]
用全部webface训练，我同学做出来的结果是96.8提升到97.2%。

**Comment by kensun0** [comment]
是单网络还是多网络融合？
我特征层是RELU激活函数，就用这个JB代码，结果反倒变差。从特征层提取的特征要做什么处理吗？

**Comment by happynear** [comment]
具体的我也不清楚，不是我做的。
应该最多就归一化一下吧。

**Comment by kensun0** [comment]
好吧，我再试试。THX~~
