### ISSUE TITLE
Download Location for washed CASIA-WebFace

### ISSUE THREAD

**Issue by yagizy** [happynear/FaceVerification#71]
Hi @happynear,

The link for washed CASIA-WebFace dataset is expired. Can you provide a new link? -- Thank you.

**Comment by happynear** [comment]
The cleaned list is still available.

**Comment by yagizy** [comment]
Thank you. I was able to get it with a VPN.

**Comment by nyyznyyz1991** [comment]
@yagizy 
Could you share the url where to download the cleand list? Thanks~

**Comment by yagizy** [comment]
I think I used the link on the project page. It should be this: http://pan.baidu.com/s/1hrKpbm8
