### ISSUE TITLE
Final layers for contrastive loss

### ISSUE THREAD

**Issue by jinbiaoyu** [happynear/FaceVerification#75]
Hello, I have a quetion didn't understand, is the final layer for face verification and identification is same,?which means the embedding size for contrastive is class nums of identity.

**Comment by happynear** [comment]
The feature dimension has no relation with the class num. Contrastive loss is applied right after the feature layer, also has no relation with the class num.

**Comment by jinbiaoyu** [comment]
@happynear Thank you! But the deepid 2 modle also has the identification signal, so there are should be softmax layer after the feature layer, so how can I share the feature layers for both softmax and contrastive loss layers, If there are additional train weights map the feature layers to  softmax layer?

**Comment by happynear** [comment]
Yes, add an additional inner-product layer for softmax loss.

**Comment by jinbiaoyu** [comment]
@happynear Okay, thank you very much！
